#!/usr/bin/env bash

alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - h : yabai -m window --focus west
alt - l : yabai -m window --focus east

alt - s: yabai -m display --focus west
alt - g: yabai -m display --focus east
shift + alt - s: yabai -m window --display prev 
shift + alt - g: yabai -m window --display next

shift + alt - f : yabai -m window --toggle float --grid 4:4:1:1:2:2

shift + alt - m : yabai -m window --toggle zoom-fullscreen

# collides with harpoon
shift + alt - e : yabai -m space --balance

ctrl + shift - j : yabai -m window --warp south
ctrl + shift - k : yabai -m window --warp north
ctrl + shift - h : yabai -m window --warp west
ctrl + shift - l : yabai -m window --warp east
